name: Deploy Lambda Functions to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws

    steps:
    # 1. Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup cache for node_modules
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # 3. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 4. Install dependencies
    - name: Install dependencies
      run: npm install
